### ISSUE TITLE
Environment information

### ISSUE THREAD

**Issue by gsabran** [EKami/planet-amazon-deforestation#11]
Thanks a lot for sharing this notebook! Can you share some info about the environment you're running it on? I'm having quite different and worst results that what is printed in the notebook when running it :(

**Comment by godardt** [comment]
Hello @gsabran . I just reran this notebook to make sure everything is ok with the code from the `master` branch and I scored exactly `0.90782` on the public LB. You can probably even get a better result by using more epochs (ex `[20, 5, 5]`) but the notebook definitely works. Did you generate it with the tool from the `Readme.md`? As for my configuration I'm running on Ubuntu 16.04 LTS/Python 3.6/Tensorflow 1.1 with a GTX 1070 and i7 7700k but I doubt it has any impact on the final predictions.

**Comment by gsabran** [comment]
Thanks! Yes I generated it with the tools from the ReadMe, and it was running with no error. I was just very surprised to see the difference in F2 score. I've seen big differences between my macbook that's running on CPU and my p2 instance that's close to 0.91 (macbook was in the 0.7-0.8..!). Do you know why the notebook has a f2 score of 0.922? Is it because the validation data is mixed at epochs array (the [20, 5, 5]) and therefore part of the training data of the previous epochs?

**Comment by godardt** [comment]
> Is it because the validation data is mixed at epochs array (the [20, 5, 5]) and therefore part of the training data of the previous epochs?

That may be the cause yes. But as for the difference between your macbook and your P2 instance I really can't tell. Another person seemed to have the same issue on Kaggle
