### ISSUE TITLE
Validation data is used for training

### ISSUE THREAD

**Issue by gsabran** [EKami/planet-amazon-deforestation#12]
The validation data is sampled in `train_model` and in the notebook train_model is called several times, therefore validating on data that was previously used for training:

```python
train_losses, val_losses = [], []
epochs_arr = [20, 5, 5]
learn_rates = [0.001, 0.0001, 0.00001]
for learn_rate, epochs in zip(learn_rates, epochs_arr):
    tmp_train_losses, tmp_val_losses, fbeta_score = classifier.train_model(x_train, y_train, learn_rate, epochs, 
                                                                           batch_size, validation_split_size=validation_split_size, 
                                                                           train_callbacks=[checkpoint])
    train_losses += tmp_train_losses
    val_losses += tmp_val_losses
```
(https://github.com/EKami/planet-amazon-deforestation/blob/d37ecdf2e8dfdf7f388e6f599564a5d14f8adb47/notebooks/amazon_forest_notebook.py#L240)

I don't think this is intentional so I'm raising the issue :)

**Comment by godardt** [comment]
Oh thanks for reporting this! Indeed we should have the same validation set for each pass in the `for` loop. Good catch! 👏

**Comment by YUXUANCHENG** [comment]
I thought author did this deliberately for cross validation XD

**Comment by godardt** [comment]
This issue has been resolved since the private code has been merged with the public one. Closing it.
