### ISSUE TITLE
SyntaxError in /src/keras_helper.py

### ISSUE THREAD

**Issue by alicesue** [EKami/planet-amazon-deforestation#13]
When I run the amazon_forest_notebook.py, there is a syntax error.
Traceback (most recent call last):
  File "amazon_forest_notebook.py", line 43, in <module>
    from keras_helper import AmazonKerasClassifier
  File "../src/keras_helper.py", line 35
    self.classifier.add(BatchNormalization(input_shape=(*img_size, img_channels)))  
                                                        ^
SyntaxError: invalid syntax.
Why do I have this error? Thank you!

**Comment by godardt** [comment]
Weird... I see no syntax error there. Are you sure you are using Python 3 and not Python 2? On line 34 we have: `self.classifier.add(BatchNormalization(input_shape=(*img_size, img_channels)))` where `*img_size` is called "argument unpacking" which I believe does not exist in Python 2 and causes the line 35 to fail.

**Comment by alicesue** [comment]
Thanks. I have solved this problem when I used Python 3.5.
