### ISSUE TITLE
Error associated with called 'check'

### ISSUE THREAD

**Issue by weedcentipede** [EKami/planet-amazon-deforestation#17]
Hi, trying to run  ```amazon_forest_notebook.py``` I get the following error:
```
Traceback (most recent call last):
  File "amazon_forest_notebook.py", line 45, in <module>
    import data_helper
  File "/home/bio/anaconda3/lib/python3.6/site-packages/data_helper/__init__.py", line 3, in <module>
    import check
ModuleNotFoundError: No module named 'check'
```
How can I solved, 
Thanks in advance, 
Luis Alfonso

**Comment by godardt** [comment]
There is no such module in `data_helper`. Are you sure you didn't modify the source code? Also, you are not supposed to run `amazon_forest_notebook.py` directly, you should be creating a `.ipynb` file with it. Please refer yourself to the Readme.
